apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: scrypted
  namespace: homeautomation
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: scrypted
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scrypted
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TZ
          value: "America/New_York"
        image: koush/scrypted:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 10080
          timeoutSeconds: 1
        name: scrypted
        ports:
        - containerPort: 10080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 10080
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 10080
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
